// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsTo5xUgYH7CpOYAlO_T8UMCZlU-i8qDM',
    appId: '1:466114471347:web:6ac50b0a90c0a89babd7c6',
    messagingSenderId: '466114471347',
    projectId: 'movieee-bc620',
    authDomain: 'movieee-bc620.firebaseapp.com',
    storageBucket: 'movieee-bc620.appspot.com',
    measurementId: 'G-CMSZEH04S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAde8Z8CbEZxF0BMbpvjUTAl05wzKjdtb0',
    appId: '1:466114471347:android:de7fa243bd82eae7abd7c6',
    messagingSenderId: '466114471347',
    projectId: 'movieee-bc620',
    storageBucket: 'movieee-bc620.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz54lUmFKYopQsEWwbmMN9EFBOpYik3vk',
    appId: '1:466114471347:ios:8c777bd3e40d8d7cabd7c6',
    messagingSenderId: '466114471347',
    projectId: 'movieee-bc620',
    storageBucket: 'movieee-bc620.appspot.com',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz54lUmFKYopQsEWwbmMN9EFBOpYik3vk',
    appId: '1:466114471347:ios:8c777bd3e40d8d7cabd7c6',
    messagingSenderId: '466114471347',
    projectId: 'movieee-bc620',
    storageBucket: 'movieee-bc620.appspot.com',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsTo5xUgYH7CpOYAlO_T8UMCZlU-i8qDM',
    appId: '1:466114471347:web:9d5d88d78761af02abd7c6',
    messagingSenderId: '466114471347',
    projectId: 'movieee-bc620',
    authDomain: 'movieee-bc620.firebaseapp.com',
    storageBucket: 'movieee-bc620.appspot.com',
    measurementId: 'G-NGW2BZTKYV',
  );
}
